repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: check-yaml
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
    -   id: autoflake
        args:
            - -i
            - -r
            - --remove-all-unused-imports
            - --expand-star-imports
            - --ignore-init-module-imports
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        args: [--python-version=3.11]
